--type IO :: * -> *
--getChar :: IO Char -- pobiera znak 
--putChar :: Char -> IO () --przyjmuję znak i go wypisuje jako propagacja funkcji
--getLine :: IO String --pobiera ciąg znków
--putStr :: String -> IO () --pobiera ciąg znaków i go wypsisuje w tej samej lini
--putStrLn :: String -> IO () --pobiera ciąg znaków i go wypsisuje w następnej lini
--print :: Show a => a -> IO () --przyjmujący parametr musi mieć zdefiniowany show
--return :: Monad m => a -> m a 